export const i18n = {
  zh: {
    title: '和光心苑',
    subtitle: '—— 愿您心有暖阳，步履从容，在平凡岁月里也能温柔常伴',
    navAuthIn: '欢迎入住',
    navAuthHome: '欢迎回家',
    navTimeline: '时光记录',
    navLang: '语言选择',
    navProfile: '我的形象',
    camTest: '摄像头预览',
    camOpt: '可选，用于更准确地感知表情',
    camOn: '摄像头已开启',
    camCap: '画面采集中...',
    micTest: '麦克风调试',
    micOpt: '可选，用于本地调试麦克风收音效果',
    emoTitle: '当前情绪感知',
    emoState: '放松',
    emoDesc: '呼吸平稳，状态舒适',
    emoQuote: '“感觉到您现在的状态很不错，像午后拂过窗畔的微风一样轻柔。”',
    logTitle: '情绪微光记录',
    log1Emo: '平静', log1Desc: '表达较平稳',
    log2Emo: '怀念', log2Desc: '提到过去时光',
    log3Emo: '放松', log3Desc: '交流后情绪舒缓',
    log4Emo: '安心', log4Desc: '感受到被理解',
    bubble1: '“今天外面阳光很好呢，有什么开心的事想和我分享吗？”',
    bubble2: '“我会一直在这里倾听。不用急，按你自己的节奏慢慢说就好。”',
    statuses: ['正在倾听...', '正在识别...', '识别完成', '正在整理回复...', '温柔回应中'],
    inputTag: '我的心声',
    inputPlaceholder: '在这里轻轻敲下您的心声，或点击右侧麦克风向我诉说...',
    recording: '正在安静倾听您的声音...',
    camModalTitle: '摄像头预览',
    camReq: '正在请求摄像头权限...',
    camSuccess: '开启成功',
    camErr: '无法访问摄像头，请检查权限设置。',
    done: '完成', cancel: '取消',
    micModalTitle: '麦克风调试',
    micSpeak: '请对准麦克风说话，检查收音效果...',
    micRec: '正在检测麦克风收音...',
    micRes: '测试结果',
    micSuccess: '已完成',
    micRetry: '再试一次',
    micClose: '关闭',
    authLoginTitle: '欢迎回来',
    authRegTitle: '开启心之旅',
    authLoginSub: '在这里，您的每一个情绪都会被倾听',
    authRegSub: '注册一个温暖的专属空间',
    username: '用户名',
    phone: '手机号',
    password: '密码',
    code: '验证码',
    getCode: '获取验证码',
    loginBtn: '温柔登录',
    regBtn: '注册并入住',
    noAcc: '若您还未入住，',
    goReg: '请先注册',
    hasAcc: '已有心苑通证？',
    goLogin: '直接入住',
    micTestText: '“今天阳光很好，感觉心里也暖暖的。”',
    phaseTitle: 'Phase C 实时会话基线',
    phaseDesc: '当前 React 前端采用 WS-first 文本流程：session create、页面 restore 与窄范围 reconnect recovery 继续复用 gateway 契约，正常文本完成以 WebSocket realtime 为准。',
    createSession: '创建会话',
    restoreState: '恢复会话',
    restoring: '恢复中...',
    restoreReady: '检测到本地会话，可恢复历史消息。',
    noStoredSession: '当前没有本地缓存的会话。',
    clearSession: '清除会话',
    submitText: '发送文本',
    sending: '发送中...',
    sessionLabel: '会话 ID',
    traceLabel: 'Trace ID',
    stageLabel: '当前阶段',
    statusLabel: '会话状态',
    messageCountLabel: '消息数',
    sessionPending: '未创建',
    sessionIdle: '等待创建或恢复会话',
    sessionCreating: '正在创建会话...',
    sessionRestoring: '正在恢复会话状态...',
    sessionReady: '会话已准备好，可以开始聊天了。',
    sessionSubmitting: '消息已发送，请稍候片刻。',
    sessionRestoreFailed: '暂时无法恢复会话，请重新开始一次对话。',
    sessionSubmitSuccess: '已收到陪伴回复。',
    sessionSubmitNeedSession: '请先创建或恢复会话。',
    sessionSubmitEmpty: '请输入内容后再发送。',
    sessionCreateFailed: '暂时无法开始对话，请稍后再试。',
    sessionConnectionNotReady: '连接尚未准备好，请稍后再试。',
    sessionBusy: '正在处理上一条消息，请稍候。',
    sessionExpired: '当前会话已结束，请重新开始。',
    sessionInvalidAccepted: '消息已发出，但确认状态异常，请再试一次。',
    sessionInvalidReply: '暂时没能生成回复，请再试一次。',
    sessionInvalidRealtime: '连接出现异常，请稍后重试。',
    sessionNetworkError: '网络连接异常，请检查服务是否已启动。',
    assistantReplies: '对话记录',
    assistantEmpty: '创建或恢复会话后，这里会显示用户消息和助手回复。',
    userRoleLabel: '你',
    assistantRoleLabel: '陪伴助手',
    systemRoleLabel: '系统',
    restoreSource: '恢复来源',
    storageKeyLabel: '存储键',
    sourceEmotionApp: 'emotion_app',
    sessionIntroTitle: '开始一段陪伴式对话',
    sessionIntroBody: '创建或恢复会话后，你可以通过文字、语音与数字人继续交流。',
    exportRecord: '导出记录',
    replayRecord: '回放记录',
    avatarSelection: '选择陪伴角色',
    activeAvatarPrefix: '当前对话角色：',
    nextAvatarPrefix: '下次创建会话时将使用：',
    sessionInteractionHint: '准备就绪后，可以直接输入文字或使用语音。',
    readyToChat: '准备好了，开始聊天吧',
    replayViewing: '正在查看会话记录',
    startRecording: '开始语音输入',
    stopRecording: '结束语音输入',
    startMicTest: '开始测试',
    stopMicTest: '结束测试',
    recordingHint: '正在聆听，请自然说话。',
    micTestingHint: '正在测试麦克风收音',
    cameraActiveHint: '正在帮助更准确地感知表情。',
    cameraModalPreviewing: '画面仅用于当前会话中的表情感知。',
    cameraModalReady: '开启预览后，可辅助识别当前状态。',
    cameraOpen: '开启预览',
    cameraClose: '关闭预览',
    cameraAdjust: '调整设置',
    micStopHint: '再次点击即可结束本次语音输入。',
    micStartHint: '点击开始后，就可以直接开口说话。',
    micTestStartHint: '这里只用于调试麦克风，不会发送成一轮对话。',
    micTestStopHint: '结束后仅保留本地调试结果，不会提交会话。',
    micTestingReady: '请说一句话，检查麦克风调试识别是否正常。',
    micTestingActive: '正在本地调试麦克风收音...',
    replayModeActive: '回放模式已接管当前界面，实时交互已暂停。',
    replayComplete: '回放完成，可重新回放或重新开始对话。',
    emotionConflictFallback: '当前信息存在分歧，建议继续温和确认。',
  },
  en: {
    title: 'Sanctuary of Light',
    subtitle: '—— May your heart hold warm sunlight and gentle peace every day',
    navAuthIn: 'Check In',
    navAuthHome: 'Welcome Home',
    navTimeline: 'Time Log',
    navLang: 'Language',
    navProfile: 'My Avatar',
    camTest: 'Camera preview',
    camOpt: 'Optional, helps read expressions more accurately',
    camOn: 'Camera is ON',
    camCap: 'Capturing...',
    micTest: 'Mic debug',
    micOpt: 'Optional, debug local microphone pickup',
    emoTitle: 'Current Emotion',
    emoState: 'Relaxed',
    emoDesc: 'Steady breathing, comfortable',
    emoQuote: '"I feel that you are in a good state, as gentle as the afternoon breeze."',
    logTitle: 'Emotion Log',
    log1Emo: 'Calm', log1Desc: 'Steady expression',
    log2Emo: 'Nostalgic', log2Desc: 'Mentioned the past',
    log3Emo: 'Relaxed', log3Desc: 'Soothed after chat',
    log4Emo: 'Peaceful', log4Desc: 'Felt understood',
    bubble1: '"The sun is beautiful today, anything happy you want to share?"',
    bubble2: '"I will always be here to listen. Take your time, at your own pace."',
    statuses: ['Listening...', 'Recognizing...', 'Recognition Complete', 'Preparing response...', 'Responding gently...'],
    inputTag: 'My Voice',
    inputPlaceholder: 'Type your thoughts here, or click the microphone to speak...',
    recording: 'Listening quietly to your voice...',
    camModalTitle: 'Camera Check',
    camReq: 'Requesting camera access...',
    camSuccess: 'Success',
    camErr: 'Cannot access camera, please check permissions.',
    done: 'Done', cancel: 'Cancel',
    micModalTitle: 'Mic debug',
    micSpeak: 'Speak into the mic to check pickup...',
    micRec: 'Testing microphone pickup...',
    micRes: 'Test result',
    micSuccess: 'Success',
    micRetry: 'Retry',
    micClose: 'Close',
    authLoginTitle: 'Welcome Back',
    authRegTitle: 'Start Journey',
    authLoginSub: 'Here, every emotion is heard',
    authRegSub: 'Register your warm exclusive space',
    username: 'Username',
    phone: 'Phone',
    password: 'Password',
    code: 'Code',
    getCode: 'Get Code',
    loginBtn: 'Gentle Login',
    regBtn: 'Register & Enter',
    noAcc: "If you haven't checked in, ",
    goReg: 'Register first',
    hasAcc: 'Already have an access pass? ',
    goLogin: 'Direct Login',
    micTestText: '"The sun is beautiful today, my heart feels warm."',
    phaseTitle: 'Phase C realtime session baseline',
    phaseDesc: 'The React frontend now uses a WS-first text flow. Session create, page restore, and narrow reconnect recovery still reuse the existing gateway contract, while normal text completion relies on WebSocket realtime.',
    createSession: 'Create session',
    restoreState: 'Restore session',
    restoring: 'Restoring...',
    restoreReady: 'A stored session was found and can be restored.',
    noStoredSession: 'No stored session is available yet.',
    clearSession: 'Clear session',
    submitText: 'Send text',
    sending: 'Sending...',
    sessionLabel: 'Session ID',
    traceLabel: 'Trace ID',
    stageLabel: 'Stage',
    statusLabel: 'Status',
    messageCountLabel: 'Messages',
    sessionPending: 'Not created',
    sessionIdle: 'Create or restore a session to continue.',
    sessionCreating: 'Creating session...',
    sessionRestoring: 'Restoring session state...',
    sessionReady: 'Your conversation is ready.',
    sessionSubmitting: 'Your message was sent. Please wait a moment.',
    sessionRestoreFailed: 'We could not restore the conversation right now. Please start a new one.',
    sessionSubmitSuccess: 'A companion reply has arrived.',
    sessionSubmitNeedSession: 'Create or restore a conversation first.',
    sessionSubmitEmpty: 'Please enter a message before sending.',
    sessionCreateFailed: 'We could not start the conversation right now. Please try again soon.',
    sessionConnectionNotReady: 'The connection is still getting ready. Please try again in a moment.',
    sessionBusy: 'Still processing your last message. Please wait a moment.',
    sessionExpired: 'This conversation has ended. Please start a new one.',
    sessionInvalidAccepted: 'Your message was sent, but confirmation looked unusual. Please try again.',
    sessionInvalidReply: 'We could not generate a reply this time. Please try again.',
    sessionInvalidRealtime: 'The connection had a problem. Please try again.',
    sessionNetworkError: 'Network error. Please check that the services are running.',
    assistantReplies: 'Conversation',
    assistantEmpty: 'User and companion messages will appear here after you create or restore a conversation.',
    userRoleLabel: 'You',
    assistantRoleLabel: 'Companion',
    systemRoleLabel: 'System',
    restoreSource: 'Restore source',
    storageKeyLabel: 'Storage key',
    sourceEmotionApp: 'emotion_app',
    sessionIntroTitle: 'Start a gentle conversation',
    sessionIntroBody: 'After creating or restoring a conversation, you can continue by text, voice, and avatar.',
    exportRecord: 'Export record',
    replayRecord: 'Replay record',
    avatarSelection: 'Choose a companion',
    activeAvatarPrefix: 'Current companion: ',
    nextAvatarPrefix: 'Next conversation will use: ',
    sessionInteractionHint: 'Once ready, you can type or use voice right away.',
    readyToChat: 'Ready when you are',
    replayViewing: 'Viewing a saved conversation',
    startRecording: 'Start voice input',
    stopRecording: 'Stop voice input',
    startMicTest: 'Start test',
    stopMicTest: 'Stop test',
    recordingHint: 'I am listening. Speak naturally.',
    micTestingHint: 'Testing microphone pickup',
    cameraActiveHint: 'Helping read your expression more accurately.',
    cameraModalPreviewing: 'This video is used only for emotion sensing in this conversation.',
    cameraModalReady: 'Turn on preview to help read your current state.',
    cameraOpen: 'Turn on preview',
    cameraClose: 'Turn off preview',
    cameraAdjust: 'Adjust settings',
    micStopHint: 'Tap again to finish this voice input.',
    micStartHint: 'Tap start and speak whenever you are ready.',
    micTestStartHint: 'This area is for microphone debugging only and will not send a conversation turn.',
    micTestStopHint: 'Stopping keeps the debug result local and does not submit to the session.',
    micTestingReady: 'Say a short phrase to verify local microphone recognition.',
    micTestingActive: 'Debugging the microphone locally...',
    replayModeActive: 'Replay mode is controlling the screen right now. Live interaction is paused.',
    replayComplete: 'Replay finished. You can replay again or start a new conversation.',
    emotionConflictFallback: 'The signals do not fully match yet. It may help to gently check in again.',
  },
  de: {
    title: 'Lichtoase',
    subtitle: '—— Möge dein Herz stets warmes Sonnenlicht und sanften Frieden in sich tragen',
    navAuthIn: 'Einchecken',
    navAuthHome: 'Willkommen zurück',
    navTimeline: 'Zeitprotokoll',
    navLang: 'Sprache',
    navProfile: 'Mein Avatar',
    camTest: 'Kameravorschau',
    camOpt: 'Optional, hilft bei genauerer Emotionserkennung',
    camOn: 'Kamera ist AN',
    camCap: 'Aufnahme...',
    micTest: 'Mikrofontest',
    micOpt: 'Optional, zum Testen von Mikrofonzugriff und Aufnahme',
    emoTitle: 'Aktuelle Emotion',
    emoState: 'Entspannt',
    emoDesc: 'Ruhige Atmung, angenehm',
    emoQuote: '"Ich spüre, dass du in einem guten Zustand bist, sanft wie die Nachmittagsbrise."',
    logTitle: 'Emotionsprotokoll',
    log1Emo: 'Ruhig', log1Desc: 'Stetiger Ausdruck',
    log2Emo: 'Nostalgisch', log2Desc: 'Vergangenheit erwähnt',
    log3Emo: 'Entspannt', log3Desc: 'Beruhigt nach Chat',
    log4Emo: 'Friedlich', log4Desc: 'Fühlte sich verstanden',
    bubble1: '"Die Sonne ist heute wunderschön. Möchtest du etwas Erfreuliches teilen?"',
    bubble2: '"Ich werde immer hier sein, um zuzuhören. Lass dir Zeit, in deinem Tempo."',
    statuses: ['Höre zu...', 'Erkenne...', 'Erkennung abgeschlossen', 'Bereite Antwort vor...', 'Antworte sanft...'],
    inputTag: 'Meine Stimme',
    inputPlaceholder: 'Tippe deine Gedanken hier, oder klicke auf das Mikrofon...',
    recording: 'Höre deiner Stimme ruhig zu...',
    camModalTitle: 'Kamera-Check',
    camReq: 'Kamerazugriff wird angefordert...',
    camSuccess: 'Erfolgreich',
    camErr: 'Kamerazugriff nicht möglich. Bitte prüfen.',
    done: 'Fertig', cancel: 'Abbrechen',
    micModalTitle: 'Mikrofontest',
    micSpeak: 'Sprich ins Mikrofon, um die Aufnahme zu prüfen...',
    micRec: 'Mikrofonaufnahme wird getestet...',
    micRes: 'Testergebnis',
    micSuccess: 'Erfolgreich',
    micRetry: 'Wiederholen',
    micClose: 'Schließen',
    authLoginTitle: 'Willkommen zurück',
    authRegTitle: 'Reise beginnen',
    authLoginSub: 'Hier wird jede Emotion gehört',
    authRegSub: 'Registriere deinen warmen Raum',
    username: 'Benutzername',
    phone: 'Telefon',
    password: 'Passwort',
    code: 'Code',
    getCode: 'Code holen',
    loginBtn: 'Sanftes Login',
    regBtn: 'Registrieren & Eintreten',
    noAcc: 'Noch nicht eingecheckt? ',
    goReg: 'Zuerst registrieren',
    hasAcc: 'Schon einen Zugangspass? ',
    goLogin: 'Direktes Login',
    micTestText: '"Die Sonne scheint heute schön, mein Herz fühlt sich warm an."',
    phaseTitle: 'Phase-C-Realtime-Sitzungsbasis',
    phaseDesc: 'Das React-Frontend nutzt jetzt einen WS-first-Textfluss. Sitzungserstellung, Seitenwiederherstellung und eine enge Reconnect-Recovery verwenden weiter den bestehenden Gateway-Vertrag, während normale Textabschlüsse über WebSocket-Realtime laufen.',
    createSession: 'Sitzung erstellen',
    restoreState: 'Sitzung laden',
    restoring: 'Wird geladen...',
    restoreReady: 'Eine gespeicherte Sitzung wurde gefunden und kann wiederhergestellt werden.',
    noStoredSession: 'Derzeit ist keine gespeicherte Sitzung vorhanden.',
    clearSession: 'Sitzung löschen',
    submitText: 'Text senden',
    sending: 'Wird gesendet...',
    sessionLabel: 'Sitzungs-ID',
    traceLabel: 'Trace-ID',
    stageLabel: 'Phase',
    statusLabel: 'Status',
    messageCountLabel: 'Nachrichten',
    sessionPending: 'Nicht erstellt',
    sessionIdle: 'Erstelle oder lade zuerst eine Sitzung.',
    sessionCreating: 'Sitzung wird erstellt...',
    sessionRestoring: 'Sitzungsstatus wird geladen...',
    sessionReady: 'Dein Gespräch ist bereit.',
    sessionSubmitting: 'Deine Nachricht wurde gesendet. Bitte warte einen Moment.',
    sessionRestoreFailed: 'Das Gespräch konnte gerade nicht wiederhergestellt werden. Bitte starte ein neues.',
    sessionSubmitSuccess: 'Eine Antwort ist eingetroffen.',
    sessionSubmitNeedSession: 'Bitte erst ein Gespräch erstellen oder wiederherstellen.',
    sessionSubmitEmpty: 'Bitte gib vor dem Senden eine Nachricht ein.',
    sessionCreateFailed: 'Das Gespräch konnte gerade nicht gestartet werden. Bitte versuche es später erneut.',
    sessionConnectionNotReady: 'Die Verbindung wird noch aufgebaut. Bitte versuche es gleich noch einmal.',
    sessionBusy: 'Die letzte Nachricht wird noch verarbeitet. Bitte warte kurz.',
    sessionExpired: 'Dieses Gespräch ist beendet. Bitte starte ein neues.',
    sessionInvalidAccepted: 'Deine Nachricht wurde gesendet, aber die Bestätigung war ungewöhnlich. Bitte versuche es erneut.',
    sessionInvalidReply: 'Diesmal konnte keine Antwort erzeugt werden. Bitte versuche es erneut.',
    sessionInvalidRealtime: 'Bei der Verbindung ist ein Problem aufgetreten. Bitte versuche es erneut.',
    sessionNetworkError: 'Netzwerkfehler. Bitte prüfe, ob die Dienste gestartet sind.',
    assistantReplies: 'Gespräch',
    assistantEmpty: 'Nach dem Erstellen oder Wiederherstellen eines Gesprächs erscheinen hier deine Nachrichten und die Antworten.',
    userRoleLabel: 'Du',
    assistantRoleLabel: 'Begleiter',
    systemRoleLabel: 'System',
    restoreSource: 'Wiederherstellungsquelle',
    storageKeyLabel: 'Speicherschlüssel',
    sourceEmotionApp: 'emotion_app',
    sessionIntroTitle: 'Beginne ein behutsames Gespräch',
    sessionIntroBody: 'Nach dem Erstellen oder Wiederherstellen kannst du per Text, Stimme und Avatar weiterreden.',
    exportRecord: 'Verlauf exportieren',
    replayRecord: 'Verlauf abspielen',
    avatarSelection: 'Begleiter wählen',
    activeAvatarPrefix: 'Aktueller Begleiter: ',
    nextAvatarPrefix: 'Beim nächsten Gespräch verwendet: ',
    sessionInteractionHint: 'Sobald alles bereit ist, kannst du direkt tippen oder sprechen.',
    readyToChat: 'Bereit, wenn du es bist',
    replayViewing: 'Gespeichertes Gespräch wird angezeigt',
    startRecording: 'Spracheingabe starten',
    stopRecording: 'Spracheingabe beenden',
    startMicTest: 'Test starten',
    stopMicTest: 'Test beenden',
    recordingHint: 'Ich höre zu. Sprich ganz natürlich.',
    micTestingHint: 'Mikrofonaufnahme wird getestet',
    cameraActiveHint: 'Hilft dabei, deinen Ausdruck genauer wahrzunehmen.',
    cameraModalPreviewing: 'Dieses Bild wird in diesem Gespräch nur zur Stimmungserkennung verwendet.',
    cameraModalReady: 'Aktiviere die Vorschau, damit dein aktueller Zustand besser erkannt werden kann.',
    cameraOpen: 'Vorschau starten',
    cameraClose: 'Vorschau beenden',
    cameraAdjust: 'Einstellungen',
    micStopHint: 'Tippe erneut, um diese Spracheingabe zu beenden.',
    micStartHint: 'Tippe auf Start und sprich, sobald du bereit bist.',
    micTestStartHint: 'Dieser Bereich dient nur zum Mikrofontest und sendet keine Gesprächsrunde.',
    micTestStopHint: 'Beim Beenden bleibt der Test lokal und wird nicht an die Sitzung gesendet.',
    micTestingReady: 'Sprich kurz, um zu prüfen, ob das Mikrofon funktioniert.',
    micTestingActive: 'Das Mikrofon wird lokal getestet...',
    replayModeActive: 'Der Wiedergabemodus steuert gerade die Ansicht. Live-Interaktion ist pausiert.',
    replayComplete: 'Die Wiedergabe ist beendet. Du kannst sie erneut starten oder ein neues Gespräch beginnen.',
    emotionConflictFallback: 'Die Signale passen noch nicht ganz zusammen. Ein behutsames Nachfragen kann helfen.',
  },
  fr: {
    title: 'Sanctuaire de Lumière',
    subtitle: '—— Que votre cœur garde la chaleur du soleil et une douce paix chaque jour',
    navAuthIn: "S'enregistrer",
    navAuthHome: 'Bienvenue',
    navTimeline: 'Journal du temps',
    navLang: 'Langue',
    navProfile: 'Mon Avatar',
    camTest: 'Aperçu caméra',
    camOpt: 'Optionnel, aide à mieux percevoir les expressions',
    camOn: 'Caméra Activée',
    camCap: 'Capture en cours...',
    micTest: 'Test micro',
    micOpt: 'Optionnel, pour tester l’accès micro et la capture',
    emoTitle: 'Émotion Actuelle',
    emoState: 'Détendu',
    emoDesc: 'Respiration calme, confortable',
    emoQuote: '"Je sens que vous êtes dans un bon état, doux comme la brise de l\'après-midi."',
    logTitle: "Journal d'Émotions",
    log1Emo: 'Calme', log1Desc: 'Expression stable',
    log2Emo: 'Nostalgique', log2Desc: 'A mentionné le passé',
    log3Emo: 'Détendu', log3Desc: 'Apaisé après discussion',
    log4Emo: 'Paisible', log4Desc: "S'est senti compris",
    bubble1: '"Le soleil est magnifique aujourd\'hui, quelque chose de joyeux à partager ?"',
    bubble2: '"Je serai toujours là pour écouter. Prenez votre temps, à votre propre rythme."',
    statuses: ['Écoute en cours...', 'Reconnaissance...', 'Reconnaissance terminée', 'Préparation de la réponse...', 'Réponse douce...'],
    inputTag: 'Ma Voix',
    inputPlaceholder: 'Tapez vos pensées ici, ou cliquez sur le micro pour parler...',
    recording: 'Écoute silencieuse de votre voix...',
    camModalTitle: 'Vérification Caméra',
    camReq: "Demande d'accès...",
    camSuccess: 'Succès',
    camErr: 'Impossible d\'accéder à la caméra.',
    done: 'Terminé', cancel: 'Annuler',
    micModalTitle: 'Test micro',
    micSpeak: 'Parlez dans le micro pour vérifier la capture...',
    micRec: 'Test de la captation micro...',
    micRes: 'Résultat du test',
    micSuccess: 'Succès',
    micRetry: 'Réessayer',
    micClose: 'Fermer',
    authLoginTitle: 'Bon retour',
    authRegTitle: 'Commencer le voyage',
    authLoginSub: 'Ici, chaque émotion est écoutée',
    authRegSub: 'Enregistrez votre espace chaleureux',
    username: "Nom d'utilisateur",
    phone: 'Téléphone',
    password: 'Mot de passe',
    code: 'Code',
    getCode: 'Obtenir le code',
    loginBtn: 'Connexion Douce',
    regBtn: "S'inscrire",
    noAcc: "Si vous n'êtes pas enregistré, ",
    goReg: "Inscrivez-vous d'abord",
    hasAcc: 'Déjà un pass ? ',
    goLogin: 'Connexion directe',
    micTestText: '"Le soleil est magnifique aujourd\'hui, mon cœur se sent chaleureux."',
    phaseTitle: 'Base de session temps réel phase C',
    phaseDesc: 'Le frontend React utilise désormais un flux texte WS-first. La création de session, la restauration de page et une reprise de reconnexion très limitée réutilisent toujours le contrat gateway existant, tandis que le chemin texte normal se termine via WebSocket realtime.',
    createSession: 'Créer une session',
    restoreState: 'Restaurer la session',
    restoring: 'Restauration...',
    restoreReady: 'Une session locale a été trouvée et peut être restaurée.',
    noStoredSession: 'Aucune session locale n’est encore disponible.',
    clearSession: 'Effacer la session',
    submitText: 'Envoyer le texte',
    sending: 'Envoi...',
    sessionLabel: 'ID de session',
    traceLabel: 'Trace ID',
    stageLabel: 'Étape',
    statusLabel: 'Statut',
    messageCountLabel: 'Messages',
    sessionPending: 'Non créée',
    sessionIdle: 'Créez ou restaurez une session pour continuer.',
    sessionCreating: 'Création de la session...',
    sessionRestoring: 'Restauration de l’état de session...',
    sessionReady: 'Votre conversation est prête.',
    sessionSubmitting: 'Votre message a été envoyé. Merci de patienter un instant.',
    sessionRestoreFailed: 'Impossible de restaurer la conversation pour le moment. Veuillez en commencer une nouvelle.',
    sessionSubmitSuccess: 'Une réponse vient d’arriver.',
    sessionSubmitNeedSession: 'Créez ou restaurez d’abord une conversation.',
    sessionSubmitEmpty: 'Veuillez saisir un message avant l’envoi.',
    sessionCreateFailed: 'Impossible de démarrer la conversation pour le moment. Veuillez réessayer plus tard.',
    sessionConnectionNotReady: 'La connexion se prépare encore. Veuillez réessayer dans un instant.',
    sessionBusy: 'Le dernier message est encore en cours de traitement. Merci de patienter.',
    sessionExpired: 'Cette conversation est terminée. Veuillez en commencer une nouvelle.',
    sessionInvalidAccepted: 'Votre message a bien été envoyé, mais la confirmation semble inhabituelle. Veuillez réessayer.',
    sessionInvalidReply: 'Impossible de générer une réponse cette fois-ci. Veuillez réessayer.',
    sessionInvalidRealtime: 'La connexion a rencontré un problème. Veuillez réessayer.',
    sessionNetworkError: 'Erreur réseau. Vérifiez que les services sont bien démarrés.',
    assistantReplies: 'Conversation',
    assistantEmpty: 'Vos messages et les réponses apparaîtront ici après la création ou la restauration d’une conversation.',
    userRoleLabel: 'Vous',
    assistantRoleLabel: 'Compagnon',
    systemRoleLabel: 'Système',
    restoreSource: 'Source de restauration',
    storageKeyLabel: 'Clé de stockage',
    sourceEmotionApp: 'emotion_app',
    sessionIntroTitle: 'Commencez une conversation apaisée',
    sessionIntroBody: 'Après avoir créé ou restauré une conversation, vous pouvez continuer par texte, voix et avatar.',
    exportRecord: 'Exporter l’historique',
    replayRecord: 'Relire l’historique',
    avatarSelection: 'Choisir un compagnon',
    activeAvatarPrefix: 'Compagnon actuel : ',
    nextAvatarPrefix: 'La prochaine conversation utilisera : ',
    sessionInteractionHint: 'Dès que tout est prêt, vous pouvez écrire ou parler directement.',
    readyToChat: 'Prêt quand vous l’êtes',
    replayViewing: 'Lecture d’une conversation enregistrée',
    startRecording: 'Démarrer la saisie vocale',
    stopRecording: 'Arrêter la saisie vocale',
    startMicTest: 'Démarrer le test',
    stopMicTest: 'Arrêter le test',
    recordingHint: 'Je vous écoute. Parlez naturellement.',
    micTestingHint: 'Test de la captation micro',
    cameraActiveHint: 'Aide à mieux percevoir votre expression.',
    cameraModalPreviewing: 'Cette image sert uniquement à percevoir l’état émotionnel pendant cette conversation.',
    cameraModalReady: 'Activez l’aperçu pour mieux percevoir votre état actuel.',
    cameraOpen: 'Activer l’aperçu',
    cameraClose: 'Couper l’aperçu',
    cameraAdjust: 'Ajuster',
    micStopHint: 'Touchez à nouveau pour terminer cette saisie vocale.',
    micStartHint: 'Touchez démarrer et parlez dès que vous êtes prêt.',
    micTestStartHint: 'Cette zone sert uniquement au test micro et n’enverra aucun tour de conversation.',
    micTestStopHint: 'L’arrêt conserve le test en local et ne l’envoie pas à la session.',
    micTestingReady: 'Dites une courte phrase pour vérifier le bon fonctionnement du micro.',
    micTestingActive: 'Test local du micro en cours...',
    replayModeActive: 'Le mode lecture contrôle actuellement l’écran. L’interaction en direct est en pause.',
    replayComplete: 'La lecture est terminée. Vous pouvez la relancer ou commencer une nouvelle conversation.',
    emotionConflictFallback: 'Les signaux ne concordent pas encore tout à fait. Une vérification douce peut aider.',
  },
};

export const dialogueStages = new Set(['engage', 'assess', 'intervene', 'reassess', 'handoff']);
export const dialogueRiskLevels = new Set(['low', 'medium', 'high']);

export const avatarProfiles = {
  companion_female_01: {
    avatarId: 'companion_female_01',
    profileId: 'companion',
    label: '陪伴角色 A',
    meta: '温和、稳定、陪你慢慢说',
    stageNote: '更适合温和接住情绪、慢慢展开对话。',
    idleDetail: '陪伴角色已准备好开始回应。',
    speakingDetail: '陪伴角色正在温和回应。',
    voicePreview: 'zh-CN-XiaoxiaoNeural',
  },
  coach_male_01: {
    avatarId: 'coach_male_01',
    profileId: 'coach',
    label: '引导角色 B',
    meta: '帮助梳理重点，陪你往下走',
    stageNote: '更适合帮助梳理重点，带着你往下一步走。',
    idleDetail: '引导角色已准备好继续对话。',
    speakingDetail: '引导角色正在给出更清晰的建议。',
    voicePreview: 'zh-CN-YunxiNeural',
  },
};

export const avatarExpressionPresets = {
  ready_idle: {
    presetId: 'ready_idle',
    label: 'ready_idle',
    detail: '当前保持平稳自然的待机表情。',
    valence: 0.12,
    arousal: 0.04,
  },
  open_warm: {
    presetId: 'open_warm',
    label: 'open_warm',
    detail: '建立联系阶段保持开放和低压，表情轻微上扬。',
    valence: 0.38,
    arousal: 0.16,
  },
  focused_assess: {
    presetId: 'focused_assess',
    label: 'focused_assess',
    detail: '评估阶段收敛动作，表情更专注，方便继续追问。',
    valence: 0.08,
    arousal: 0.1,
  },
  steady_support: {
    presetId: 'steady_support',
    label: 'steady_support',
    detail: '干预阶段保持稳定支持，动作柔和，不做夸张变化。',
    valence: 0.24,
    arousal: 0.14,
  },
  calm_checkin: {
    presetId: 'calm_checkin',
    label: 'calm_checkin',
    detail: '再评估阶段回到中性稳定，观察用户反馈变化。',
    valence: 0.16,
    arousal: 0.08,
  },
  guarded_handoff: {
    presetId: 'guarded_handoff',
    label: 'guarded_handoff',
    detail: '高风险或 handoff 阶段降低轻快感，保持严肃和稳定。',
    valence: -0.08,
    arousal: 0.12,
  },
};

export const DEFAULT_EXPORT_MESSAGE = '开始或恢复会话后，就可以导出当前记录。';
export const DEFAULT_REPLAY_MESSAGE = '导出当前记录后，就可以回放这段对话。';
